# ==========================================
#        AERIAMENUS - CONFIGURAÇÃO BASE
# ==========================================

modulos:
  dar-itens-ao-entrar: true  
  ativar-protecoes: true     
  ativar-scoreboard: true    
  ativar-bossbar: true
  ativar-chat: true          
  ativar-clima-sempre-dia: true
  ativar-mensagens-entrada: true
  ativar-efeitos-entrada: true
  usar-placeholderapi: true
  ativar-tablist-animada: true
  ativar-actionbar-rotativa: true
  # NOVO: Permite ao dono do servidor escolher se quer ou nao integrar com o Vault
  usar-vault: true

spawn:
  teleportar-ao-entrar: true
  altura-void: 0.0
  local:
    mundo: "world"
    x: 0.0
    y: 100.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0

bossbar:
  titulo: "&#00d4ff&lAERIA MENUS &8| &fBem-vindo, &a%player_name%"
  cor: "BLUE" 
  estilo: "SOLID" 
  progresso: 1.0

scoreboard:
  titulo: "<gradient:#00d4ff:#00ff55>&lAERIA MENUS</gradient>"
  linhas:
    - "&8&m                                   "
    - "&fPerfil:"
    - " &8• &7Jogador: &#00ff55%player_name%"
    - " &8• &7Cargo: &f%vault_rank%"
    - " &8• &7Moedas: &a$%vault_eco_balance_formatted%"
    - ""
    - "&fServidor:"
    - " &8• &7Online: &#ffaa00%server_online%&8/&7%server_max_players%"
    - " &8• &7Ping: &a%player_ping%ms"
    - ""
    - "&#00d4ffloja.aeriamenus.com"
    - "&8&m                                   "

tablist:
  tempo-atualizacao: 20
  header:
    - ""
    - "<gradient:#00d4ff:#00ff55>&lAERIA MENUS - REDE DE JOGOS</gradient>"
    - "&7Bem-vindo(a) de volta, &f%player_name%&7!"
    - ""
  footer:
    - ""
    - "&eAcesse nossa loja: &f&nloja.aeriamenus.com"
    - "&7Jogadores conectados: &a%server_online%"
    - ""

actionbar:
  tempo-entre-mensagens: 5
  mensagens:
    - "&eBem-vindo ao nosso Lobby Principal!"
    - "&aCompre VIP e ajude o servidor: &nloja.aeriamenus.com"
    - "&bUse a Bússola no seu inventário para jogar!"

protecoes:
  bloquear-quebra: true
  bloquear-colocacao: true
  bloquear-drop: true
  bloquear-fome: true
  bloquear-dano: true

itens-entrada:
  bussola:
    material: "COMPASS"
    slot: 4
    custom-model-data: 0
    nome: "&#ffaa00&lSELETOR DE SERVIDORES &7(Clique)"
    encantamentos:
      - "unbreaking:1" 
    flags:
      - "HIDE_ENCHANTS"
    lore:
      - "&7Clique para abrir o menu."
    acoes:
      - "som: UI_BUTTON_CLICK"
      - "menu: principal"
  magica:
    material: "CLOCK"
    slot: 8
    custom-model-data: 0
    nome: "&#ff44ff&lOCULTAR JOGADORES &7(Clique)"
    lore:
      - "&7Clique para esconder ou mostrar"
      - "&7os outros jogadores."
    acoes:
      - "som: UI_BUTTON_CLICK"
      - "especial: alternar_visibilidade"