name: AeriaMenus
version: 1.0.0
main: com.aeriaplugins.plugins.Main
api-version: '1.21'
softdepend: [PlaceholderAPI]
commands:
  aeriamenus:
    description: Comando principal do AeriaMenus
    aliases: [am]