nome-do-menu: "&8Painel de Controle: Navegação"

itens:
  fundo:
    material: GRAY_STAINED_GLASS_PANE
    nome: " "
  
  criar-ilha:
    material: GRASS_BLOCK
    slot: 10
    nome: "&a&l🔨 Criar Nova Ilha"
    schematic: "pmcskyblock.schem"
    lore:
      - "&7Clique aqui para estabelecer ou"
      - "&7construir sua base operacional."
      - ""
      - "&e▶ Clique para iniciar o SkyBlock."

  setar-spawn:
    material: ANVIL
    slot: 12
    nome: "&6&l🎯 Fixar Spawn da Base"
    lore:
      - "&7Define a sua localização atual como"
      - "&7o ponto de retorno oficial da ilha."
      - ""
      - "&e▶ Clique para salvar o Spawn."

  informacoes:
    material: BOOK
    slot: 14
    nome: "&e&l📊 Estatísticas Centrais"
    lore:
      - "&7Status técnico do seu território:"
      - "{lista_ilhas}"
      - ""
      - "&7Nível Atual: &b{nivel_ilha} XP"
      - ""
      - "&7Para apagar use: &c/is delete <ID>"

  teleportar:
    material: COMPASS
    slot: 16
    nome: "&b&l🚀 Vetor de Teleporte"
    lore:
      - "&7Direcione os motores e teleporte-se"
      - "&7direto para a sua base operacional."
      - ""
      - "&e▶ Clique para viajar."