settings:
  check-interval-ticks: 40

horde-night:
  days-interval: 3
  zombie-health: 80.0
  zombie-name: ""
  show-name: true
  show-health: true
  name-format: "{name} &7[&a{current}/{max}❤&7]"
  zombie-buffs:
    - "speed:0"
    - "strength:1"
    - "resistance:1"
  bossbar:
    text: "&cA Horda Está Ativa - Sobreviva!"
    color: "RED"
    style: "SOLID"

noise-system:
  enabled: true
  chunk-threshold: 100
  points:
    running: 5
    block-break: 15
    weapon-fire: 50

siege:
  allow-block-destruction: true
  breakable-blocks:
    - "OAK_PLANKS"
    - "IRON_BARS"
    - "OAK_DOOR"
  hits-required-to-break: 15

spawning:
  max-zombies-per-player: 10
  global-max-zombies: 40
  group-size: 5
  min-distance: 15
  max-distance: 35

allowed-worlds:
  - "world"
  - "cidade_apocalypse"

infested-regions:
  hospital_abandonado:
    world: "cidade_apocalypse"
    x: 120.0
    y: 64.0
    z: -340.0
    radius: 30.0
    max-zombies: 15
    group-size: 3
    zombie-health: 120.0
    zombie-name: "&9Zumbi Mutante"
  area_militar:
    world: "cidade_apocalypse"
    x: 500.0
    y: 65.0
    z: 250.0
    radius: 45.0
    max-zombies: 20
    group-size: 5
    zombie-health: 100.0
    zombie-name: "&eZumbi Militar"